spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.33.191:38066/wis
    username: root
    password: 123456
  thymeleaf:
    check-template-location: true
    prefix: classpath:/public/templates/
    encoding: UTF-8
    content-type: text/html
    suffix: .html

logging:
  level:
    org.springframework.web: DEBUG
    com.idb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: D:\\sta-dev.log
